workflows = {
	'model1':{
		'load':{
			'transforms':[
				('crop_resize',{'img_shape':(64,64)})
				],
			'im_loader':'load_images_raw',
			'loader':'load',
			'writer':'write_duplicates'
		},
		'models':['conv_model','conv_model'],
		'model_inputs':30,
		'preprocess':[
			('preprocess1',{'weight':0.1})
			],
		'train':{
			'trainer':'train_dual',
			'params':{
				'split_ratio':0.2,
				'batch_size':32
			},
			'augmentations':[
				('rotation',{'angle_range':15}),
				('shift',{'h_range':0.1,'w_range':0.1}),
				]
		},
		'submit':{
			'submitter':'submission_dual',
			'params':{
				'batch_size':32
			}
		}
	},

	'model2':{
		'load':{
			'preselect':'preselect',
			'n_preselect':6,
			'transforms':[
				('full_rescale',{}),
				('imresize',{'img_shape':(64,64)})
				],
			'im_loader':'load_images_selection',
			'loader':'load',
			'writer':'write'
		},
		'model':'conv_model',
		'model_inputs':6,
		'preprocess':[],
		'train':{
			'trainer':'train_single',
			'params':{
				'split_ratio':0.2,
				'batch_size':64
			},
			'augmentations':[
				('rotation',{'angle_range':15}),
				('shift',{'h_range':0.1,'w_range':0.1}),
				]
		},
		'submit':{
			'submitter':'submission_single',
			'params':{
				'batch_size':64
			}
		}
	},

	'model3':{
		'load':{
			'preselect':'preselect',
			'n_preselect':8,
			'transforms':[
				('full_rescale',{}),
				('imresize',{'img_shape':(64,64)})
				],
			'im_loader':'load_images_selection',
			'loader':'load',
			'writer':'write'
		},
		'model':'conv_model',
		'model_inputs':5,
		'preprocess':[
			('preprocess3',{'weight':0.05})
			],
		'train':{
			'trainer':'train_single_sampling',
			'params':{
				'split_ratio':0.2,
				'batch_size':64
			},
			'augmentations':[
				('rotation',{'angle_range':15}),
				('shift',{'h_range':0.1,'w_range':0.1}),
				]
		},
		'submit':{
			'submitter':'submission_single_bagging',
			'params':{
				'batch_size':64,
				'n_bagging':2
			}
		}
	},

	'model4':{
		'load':{
			'transforms':[
				('full_rescale',{}),
				('imresize',{'img_shape':(64,64)})
				],
			'im_loader':'load_images_raw',
			'loader':'load',
			'writer':'write_duplicates'
		},
		'models':['conv_model','conv_model'],
		'model_inputs':30,
		'preprocess':[
			('preprocess1',{'weight':0.05})
			],
		'train':{
			'trainer':'train_dual',
			'params':{
				'split_ratio':0.2,
				'batch_size':32
			},
			'augmentations':[
				('rotation',{'angle_range':15}),
				('shift',{'h_range':0.1,'w_range':0.1}),
				]
		},
		'submit':{
			'submitter':'submission_dual',
			'params':{
				'batch_size':32
			}
		}
	},

	'model5':{
		'load':{
			'preselect':'preselect',
			'n_preselect':8,
			'transforms':[
				('full_rescale',{}),
				('imresize',{'img_shape':(64,64)})
				],
			'im_loader':'load_images_selection',
			'loader':'load',
			'writer':'write'
		},
		'model':'conv_model',
		'model_inputs':5,
		'preprocess':[
			('preprocess2',{'weight':0.05})
			],
		'train':{
			'trainer':'train_single_sampling',
			'params':{
				'split_ratio':0.2,
				'batch_size':64
			},
			'augmentations':[
				('rotation',{'angle_range':15}),
				('shift',{'h_range':0.1,'w_range':0.1}),
				]
		},
		'submit':{
			'submitter':'submission_single_bagging',
			'params':{
				'batch_size':64,
				'n_bagging':2
			}
		}
	},
}